services:
  #backend api
  backend-api:
    image: dhouhalamine/api-session14
    depends_on:
      - mongo-session14
    container_name: backend-api-container
    env_file:
      - .env
    ports:
      - "3000:3001"

  #database mongo- db (nom unique)
  mongo-session14:
    image: mongo
    restart: always
    container_name: session14-mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: admin
    volumes:
      - session14_mongo_data:/data/db

  #mongo express ui (port différent) - CONFIGURATION CORRIGÉE
  mongo-express:
    image: mongo-express
    restart: always
    container_name: session14-mongo-express
    ports:
      - "8082:8081"
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo-session14
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_ENABLE_ADMIN: true
      ME_CONFIG_MONGODB_AUTH_DATABASE: admin
      ME_CONFIG_MONGODB_AUTH_USERNAME: root
      ME_CONFIG_MONGODB_AUTH_PASSWORD: admin
      ME_CONFIG_BASICAUTH_USERNAME: mongoexpressuser
      ME_CONFIG_BASICAUTH_PASSWORD: mongoexpresspass
    depends_on:
      - mongo-session14

volumes:
  session14_mongo_data: